name: "Init Flutter"
description: "Initializes Flutter repo"
runs:
  using: "composite"
  steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.10.5
        channel: 'stable'
        cache: true
    - name: Get dependencies
      shell: bash
      run: flutter pub get
    - name: Generate code
      shell: bash
      run: dart run build_runner build