name: daily_scores
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.1.0
  injectable: ^2.3.2
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  injectable_generator: ^2.4.1

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Regular.ttf
          weight: 400